version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - apt-get update
      - apt-get install nginx -y

  build:
    commands:
      - echo "Build started on `date`"
      - cp index.html /var/www/html/  # Copy your HTML file to NGINX's root directory
      - echo "Creating zip file..."
      - zip -r demo-app.zip /var/www/html/*  # Create a zip file of the HTML directory

  post_build:
    commands:
      - echo "Configuring NGINX"
      - service nginx start  # Starting NGINX service after installation

artifacts:
  files:
    - demo-app.zip  # Include the zip file in the artifacts
